PortfolioCoreProject/Controllers/SubContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace PortfolioCoreProject.Controllers
{
    public class SubContactController : Controller
    {
        ContactManager contactManager = new ContactManager(new EfContactDal());

        [HttpGet]
        public IActionResult Index()
        {
            var values = contactManager.TGetByID(1);
            return View(values);
        }

        [HttpPost]
        public IActionResult Index(Contact contact)
        {
            contactManager.TUpdate(contact);
            return RedirectToAction("Index", "Default");
        }
    }
}

PortfolioCoreProject/Views/SubContact/Index.cshtml
@model EntityLayer.Concrete.Contact
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

@using (Html.BeginForm("Index", "SubContact", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description"> Edit SubContact </p>
                <form class="forms-sample">
                    <div class="form-group">
                        <label>ID</label>
                        @Html.TextBoxFor(x => x.ContactID, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Title</label>
                        @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Phone Number</label>
                        @Html.TextBoxFor(x => x.PhoneNumber, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>E-Mail</label>
                        @Html.TextBoxFor(x => x.Mail, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Description</label>
                        @Html.TextAreaFor(x => x.Description, 6, 3, new { @class = "form-control" })
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Save</button>
                    <button class="btn btn-dark">Cancel</button>
                </form>
            </div>
        </div>
    </div>
}