PortfolioCoreProject/Controllers/ExperienceController.cs
using System;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace PortfolioCoreProject.Controllers
{
    [Authorize(Roles ="Admin")]
    public class ExperienceController : Controller
    {
        ExperienceManager experienceManager = new ExperienceManager(new EfExperienceDal());

        public IActionResult Index()
        {
            ViewBag.v1 = "Experience Edit";
            ViewBag.v2 = "Skills";
            ViewBag.v3 = "Experience Edit";
            var values = experienceManager.TGetList();
            return View(values);
        }

        [HttpGet]
        public IActionResult AddExperience()
        {
            ViewBag.v1 = "Experience Add";
            ViewBag.v2 = "Skills";
            ViewBag.v3 = "Experience Add";  
            return View();
        }

        [HttpPost]
        public IActionResult AddExperience(Experience experience)
        {
            experienceManager.TAdd(experience);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteExperience(int id)
        {
            var values = experienceManager.TGetByID(id);
            experienceManager.TDelete(values);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditExperience(int id)
        {
            ViewBag.v1 = "Experience Add";
            ViewBag.v2 = "Skills";
            ViewBag.v3 = "Experience Add";
            var values = experienceManager.TGetByID(id);
            return View(values);
        }

        [HttpPost]
        public IActionResult EditExperience(Experience experience)
        {
            experienceManager.TUpdate(experience);
            return RedirectToAction("Index");
        }
    }
}

PortfolioCoreProject/Views/Experience/AddExperience.cshtml
@model EntityLayer.Concrete.Experience

@{
    ViewData["Title"] = "AddExperience";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}


@using (Html.BeginForm("AddExperience", "Experience", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description"> New Experience </p>
                <form class="forms-sample">
                    <div class="form-group">
                        <label>Title</label>
                        <input type="text" class="form-control" name="Name">
                    </div>
                    <div class="form-group">
                        <label>Date</label>
                        <input type="text" class="form-control" name="Date">
                    </div>
                    <div class="form-group">
                        <label>Image</label>
                        <input type="text" class="form-control" name="Image URL">
                    </div>

                    <div class="form-group">
                        <label>Description</label>
                        <textarea class="form-control" name="Description" rows="6"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Save</button>
                    <button class="btn btn-dark">Cancel</button>
                </form>
            </div>
        </div>
    </div>
}

PortfolioCoreProject/Views/Experience/DeleteExperience.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

PortfolioCoreProject/Views/Experience/EditExperience.cshtml
@model EntityLayer.Concrete.Experience
@{
    ViewData["Title"] = "AddSkill";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="card-header border-0">
    <h3 class="mb-0">Edit Experience</h3>
</div>


@using (Html.BeginForm("EditExperience", "Experience", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description"> Edit Experience </p>
                <form class="forms-sample">
                    <div class="form-group">
                        <label>ID</label>
                        @Html.TextBoxFor(x => x.ExperienceID, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Title</label>
                        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Date</label>
                        @Html.TextBoxFor(x => x.Date, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Image</label>
                        @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        <label>Description</label>
                        @Html.TextAreaFor(x => x.Description, 6, 3, new { @class = "form-control" })
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Save</button>
                    <button class="btn btn-dark">Cancel</button>
                </form>
            </div>
        </div>
    </div>
}

PortfolioCoreProject/Views/Experience/Index.cshtml
@using EntityLayer.Concrete
@model List<Experience>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="card-header border-0">
    <h3 class="mb-0">Experiences</h3>
</div>
<!-- Light table -->
<div class="table-responsive">
    <table class="table align-items-center table-flush">
        <thead class="thead-light">
            <tr>
                <th scope="col" class="sort" data-sort="name">#</th>
                <th scope="col" class="sort" data-sort="budget">Title</th>
                <th scope="col" class="sort" data-sort="status">Date</th>
                <th scope="col">Delete</th>
                <th scope="col" class="sort" data-sort="completion">Edit</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody class="list">
            @foreach (var item in Model)
            {
                <tr>
                    <th>
                        @item.ExperienceID
                    </th>
                    <th class="budget">
                        @item.Name
                    </th>
                    <td>
                        @item.Date
                    </td>
                    <td><a href="/Experience/DeleteExperience/@item.ExperienceID" class="btn btn-danger">Delete</a></td>
                    <td><a href="/Experience/EditExperience/@item.ExperienceID" class="btn btn-info">Edit</a></td>
                </tr>
            }
        </tbody>
    </table>
    <a href="/Experience/AddExperience/" class="btn btn-primary">New Experience</a>
</div>